### ISSUE TITLE
配置有点问题吧..

### ISSUE THREAD

**Issue by riverai** [vc5/JD-Coin#4]
明明是下载的chromdriver，结果报错的时候提示 geckodriver可执行文件不在path中。这是不是没对？

而且我新建了一个文件夹放入了chromedriver并且添加到path中并不能找到可执行文件，反而直接把chromedriver复制到了Python目录可以了。

还有一个问题。 怎样取消不用的第二个账号登录过程？从配置文件上来改的话。

**Comment by vc5** [comment]
chromdriver没找到会自动寻找geckodriver，脚本目前同时兼容Chrome和Firefox
单账号配置示例
```json
{
    "debug": true,
    "headless": false,
    "jd": [
        {
            "username": "username1",
            "password": "password1"
        }
    ],
    "jobs_skip": []
}
```
